name: Compile on Linux
on:
  push:
    branches: [main]
    tags: ['v[0-9]*', '[0-9]+.[0-9]+*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install build-essential
      run: sudo apt-get install build-essential
    - name: Create Linux interface directory
      run: mkdir -p src/audiostretchy/interface/linux/
    - name: Compile stretch.c
      shell: bash {0}
      run: |
        gcc -fPIC -shared -o _stretch.so vendors/stretch/stretch.c
        mv _stretch.so src/audiostretchy/interface/linux/
        ls -l src/audiostretchy/interface/linux/
    - name: Commit and push if changed
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update compiled files"
        add: 'src/audiostretchy/interface/linux/_stretch.so'
