name: Compile on Windows
on:
  push:
    branches: [main]
    tags: ['v[0-9]*', '[0-9]+.[0-9]+*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Compile stretch.c
      shell: pwsh
      run: |
        cl /LD /Fe:stretch.dll /O2 /MT vendors/stretch/stretch.c
        New-Item -ItemType Directory -Path src/audiostretchy/interface/win -Force
        mv stretch.dll src/audiostretchy/interface/win/_stretch.dll
        ls -l src/audiostretchy/interface/win/
    - name: Commit and push if changed
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update Windows compiled lib"
        add: 'src/audiostretchy/interface/win/_stretch.dll'
